channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=25.1.1
- pip:
  - mlflow==3.2.0
  - cloudpickle==3.1.1
  - colorama==0.4.6
  - defusedxml==0.7.1
  - matplotlib==3.10.3
  - numpy==2.3.1
  - pandas==2.3.1
  - pytorch-lightning==2.5.3
  - scipy==1.16.0
  - torch==2.7.1
name: mlflow-env
